title:            /bin/log
description:      Log my thoughts
url:              http://note.jzr.me
signoff:          JZR
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.

links:
  - name:         Home
    url:          /
  - name:         About
    url:          https://jzr.me
    external:     true
  - name:         GitHub
    url:          http://github.com/denzeljiang
    external:     true
pygments:         true
permalink:        /:year/:month/:title/
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
    - autolink
    - tables
